### ISSUE TITLE
Add bitwise operations

### ISSUE THREAD

**Issue by elikaski** [elikaski/BF-it#13]
Add bitwise and, or, xor

**Comment by elikaski** [comment]
Also bitwise Not,
Shift left and shift right

**Comment by NeeEoo** [comment]
Shift Left and Shift Right is the same as `number*(2**n)` and `number/(2**n)`.

a is the number
b is the shift amount

Shift Left

```
while b != 0:
    a = a * 2
    b -= 1
```

Shift Right

```
while b != 0:
    a = a / 2
    b -= 1
```

Shift Right could be implemented without division and is probably smaller and faster

```
while b != 0:
    c = 0
    if a != 1:
        while a != 0:
            c += 1
            a -= 2
    a = c
    b -= 1
```

**Comment by NeeEoo** [comment]
Made a bitwise AND algorithm but it is 418 bytes long. OR and XOR would be around the same size

**Comment by NeeEoo** [comment]
I was able to get it down to 326 bytes and it now uses 10 cells.
