### ISSUE TITLE
Add block comments

### ISSUE THREAD

**Issue by NeeEoo** [elikaski/BF-it#15]
Example
```
int a = /* Comment */ 8;
```

```
int b = 10;
/* Comment
Still a comment
Also a comment */ int c = 8;
```

**Comment by elikaski** [comment]
When implementing this, need to make sure the regex will be non greedy
E.g
`/*  x  */  y /*  z  */`
Will catch just x and z as commnets, and not `x  */  y /*  z` as comment

**Comment by elikaski** [comment]
Thanks @mrkct for implementing this :)
