### ISSUE TITLE
[Small Bug] Using an assignment operator which isn't =

### ISSUE THREAD

**Issue by NeeEoo** [elikaski/BF-it#37]
```c
int y *= 3;
```
this compiles, but it shouldn't. Other compilers restrict the token after the type to only `=`, `,` (this compiler doesn't have this yet), and `;`

**Comment by elikaski** [comment]
Related to #35
Probably somewhere we check if we have "INT ID ASSIGN EXPRESSION"
Need to add a check that the ASSIGN's value is = and not other types of assignment (*=, += etc)
(Maybe function create_variable_from_definition ?
Or maybe in compile_statement before calling compile_expression_as_statement in [INT ID ([NUM])? (= EXPRESSION)? ;]?)
