### ISSUE TITLE
Support octal and binary literals

### ISSUE THREAD

**Issue by NeeEoo** [elikaski/BF-it#38]
Octal literals are defined as `0[0-7]+`
Binary literals are defined as `0b[01]+`

**Comment by elikaski** [comment]
Good idea!
Need to add it to lexical analyzer and get_NUM_token_value function

**Comment by elikaski** [comment]
Let's make octal like Python: 0o[0-7]+

**Comment by abhra2020-smart** [comment]
lol no need to do anything it already does support octals and stuff

**Comment by NeeEoo** [comment]
This is talking about integers.

```
int octal = 0b635;
int binary = 0b1101010;
```

**Comment by abhra2020-smart** [comment]
oh
