### ISSUE TITLE
implement else if without scope brackets

### ISSUE THREAD

**Issue by elikaski** [elikaski/BF-it#8]
Currently the only way to implement an "else if" is to put the if in the else's brackets:

if (x) {
 ...
} else {
 if (y) {
  ...
  }
}

need to implement elseif or something similar

**Comment by elikaski** [comment]
Basically allow a compilation of either "{" or <statement> after an if(...)
Same for else
Will behave similar to C

**Comment by NeeEoo** [comment]
Technically this works in c without implementing this i think because c supports if, else, while, for without brackets.

Example:
```c
if(test == 5) {
    print("hello");
}

// Works exactly the same as
if(test == 5)
    print("hello");
```

But this won't really work on this compiler (yet) since it doesn't store indentation.

I'll try and to implement so it converts `else if(` to `else { if(`

**Comment by elikaski** [comment]
I don't think its related to indentation. It's because of the grammar of the language (please see grammar reference in readme)
In C, "if" token is followed by "statement" which can be (among other things) new scope (in {} brackets) or expression (e.g x=1;)
In our code I think it's a matter of checking whether or not we have brackets inside compile_if function, and then either call compile_scope or call compile_statement

**Comment by NeeEoo** [comment]
```c
if(test == 5) {
print("hello");
print("world");
}
// Prints "helloworld" if test == 5 else print ""

if(test == 5)
    print("hello");
print("world");
// Prints "helloworld" if test == 5 else print "world"
```

Anyways i'm finished with the code just gonna make a pr for it.
